### ISSUE TITLE
Install failure octoPrint Latest

### ISSUE THREAD

**Issue by navypixel** [printpal-io/OctoPrint-BedCheckAI#1]
Attempted to install tonight on test printer and failed to even install;

```
Installing plugin "OctoPrint-BedCheckAI" from https://github.com/printpal-io/OctoPrint-BedCheckAI/archive/master.zip...
Error!
Unexpected error while trying to install plugin from None
```

**Comment by printpal-io** [comment]
> Attempted to install tonight on test printer and failed to even install;
> 
> ```
> Installing plugin "OctoPrint-BedCheckAI" from https://github.com/printpal-io/OctoPrint-BedCheckAI/archive/master.zip...
> Error!
> Unexpected error while trying to install plugin from None
> ```

It seems this is an issue with the plugin manager: https://community.octoprint.org/t/i-keep-getting-an-error-message-when-i-try-to-install-plugins/52267

You can try rebooting and installing again, if that doesn't work, just install from URL using: https://github.com/printpal-io/OctoPrint-BedCheckAI/archive/master.zip

**Comment by printpal-io** [comment]
@Navypixel Issue resolved with my recommendation?

**Comment by navypixel** [comment]
yes this worked afterwards using the URL. thanks
